namespace WindowsFormsApp1.UserControls
{
    partial class Customer
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Customer));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.addbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addressbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.phonenumberbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cusnamebox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.label1 = new System.Windows.Forms.Label();
            this.searchbtn = new System.Windows.Forms.Button();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.searchbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.idbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.deletebtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.updatebtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addressbox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.phonenumberbox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cusnamebox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.tabPage3.SuspendLayout();
            this.SuspendLayout();
            // 
            // contextMenuStrip1
            // 
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new System.Drawing.Size(61, 4);
            // 
            // tabControl1
            // 
            this.tabControl1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Location = new System.Drawing.Point(212, 78);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(884, 634);
            this.tabControl1.TabIndex = 4;
            this.tabControl1.SelectedIndexChanged += new System.EventHandler(this.tabControl1_SelectedIndexChanged);
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage1.Controls.Add(this.addbtn);
            this.tabPage1.Controls.Add(this.addressbox);
            this.tabPage1.Controls.Add(this.bunifuLabel3);
            this.tabPage1.Controls.Add(this.phonenumberbox);
            this.tabPage1.Controls.Add(this.bunifuLabel2);
            this.tabPage1.Controls.Add(this.cusnamebox);
            this.tabPage1.Controls.Add(this.bunifuLabel1);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(876, 608);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Add Customer";
            // 
            // addbtn
            // 
            this.addbtn.AllowAnimations = true;
            this.addbtn.AllowMouseEffects = true;
            this.addbtn.AllowToggling = false;
            this.addbtn.AnimationSpeed = 200;
            this.addbtn.AutoGenerateColors = false;
            this.addbtn.AutoRoundBorders = false;
            this.addbtn.AutoSizeLeftIcon = true;
            this.addbtn.AutoSizeRightIcon = true;
            this.addbtn.BackColor = System.Drawing.Color.Transparent;
            this.addbtn.BackColor1 = System.Drawing.Color.SteelBlue;
            this.addbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addbtn.BackgroundImage")));
            this.addbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addbtn.ButtonText = "Add";
            this.addbtn.ButtonTextMarginLeft = 0;
            this.addbtn.ColorContrastOnClick = 45;
            this.addbtn.ColorContrastOnHover = 45;
            this.addbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.addbtn.CustomizableEdges = borderEdges1;
            this.addbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addbtn.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addbtn.ForeColor = System.Drawing.Color.White;
            this.addbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addbtn.IconMarginLeft = 11;
            this.addbtn.IconPadding = 10;
            this.addbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addbtn.IconSize = 25;
            this.addbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.addbtn.IdleBorderRadius = 1;
            this.addbtn.IdleBorderThickness = 1;
            this.addbtn.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.addbtn.IdleIconLeftImage = null;
            this.addbtn.IdleIconRightImage = null;
            this.addbtn.IndicateFocus = false;
            this.addbtn.Location = new System.Drawing.Point(127, 404);
            this.addbtn.Name = "addbtn";
            this.addbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addbtn.OnDisabledState.BorderRadius = 1;
            this.addbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addbtn.OnDisabledState.BorderThickness = 1;
            this.addbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addbtn.OnDisabledState.IconLeftImage = null;
            this.addbtn.OnDisabledState.IconRightImage = null;
            this.addbtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addbtn.onHoverState.BorderRadius = 1;
            this.addbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addbtn.onHoverState.BorderThickness = 1;
            this.addbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addbtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addbtn.onHoverState.IconLeftImage = null;
            this.addbtn.onHoverState.IconRightImage = null;
            this.addbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.addbtn.OnIdleState.BorderRadius = 1;
            this.addbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addbtn.OnIdleState.BorderThickness = 1;
            this.addbtn.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.addbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addbtn.OnIdleState.IconLeftImage = null;
            this.addbtn.OnIdleState.IconRightImage = null;
            this.addbtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addbtn.OnPressedState.BorderRadius = 1;
            this.addbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addbtn.OnPressedState.BorderThickness = 1;
            this.addbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addbtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addbtn.OnPressedState.IconLeftImage = null;
            this.addbtn.OnPressedState.IconRightImage = null;
            this.addbtn.Size = new System.Drawing.Size(101, 39);
            this.addbtn.TabIndex = 6;
            this.addbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addbtn.TextMarginLeft = 0;
            this.addbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.addbtn.UseDefaultRadiusAndThickness = true;
            this.addbtn.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // addressbox
            // 
            this.addressbox.AcceptsReturn = false;
            this.addressbox.AcceptsTab = false;
            this.addressbox.AnimationSpeed = 200;
            this.addressbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressbox.BackColor = System.Drawing.Color.Transparent;
            this.addressbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressbox.BackgroundImage")));
            this.addressbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addressbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addressbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressbox.BorderRadius = 1;
            this.addressbox.BorderThickness = 1;
            this.addressbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressbox.DefaultText = "";
            this.addressbox.FillColor = System.Drawing.Color.White;
            this.addressbox.HideSelection = true;
            this.addressbox.IconLeft = null;
            this.addressbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox.IconPadding = 10;
            this.addressbox.IconRight = null;
            this.addressbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox.Lines = new string[0];
            this.addressbox.Location = new System.Drawing.Point(127, 268);
            this.addressbox.MaxLength = 32767;
            this.addressbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressbox.Modified = false;
            this.addressbox.Multiline = false;
            this.addressbox.Name = "addressbox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox.OnIdleState = stateProperties4;
            this.addressbox.Padding = new System.Windows.Forms.Padding(3);
            this.addressbox.PasswordChar = '\0';
            this.addressbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressbox.PlaceholderText = "Enter text";
            this.addressbox.ReadOnly = false;
            this.addressbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressbox.SelectedText = "";
            this.addressbox.SelectionLength = 0;
            this.addressbox.SelectionStart = 0;
            this.addressbox.ShortcutsEnabled = true;
            this.addressbox.Size = new System.Drawing.Size(634, 107);
            this.addressbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressbox.TabIndex = 5;
            this.addressbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressbox.TextMarginBottom = 0;
            this.addressbox.TextMarginLeft = 3;
            this.addressbox.TextMarginTop = 0;
            this.addressbox.TextPlaceholder = "Enter text";
            this.addressbox.UseSystemPasswordChar = false;
            this.addressbox.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(127, 245);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(66, 20);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Address : ";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // phonenumberbox
            // 
            this.phonenumberbox.AcceptsReturn = false;
            this.phonenumberbox.AcceptsTab = false;
            this.phonenumberbox.AnimationSpeed = 200;
            this.phonenumberbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonenumberbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonenumberbox.BackColor = System.Drawing.Color.Transparent;
            this.phonenumberbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonenumberbox.BackgroundImage")));
            this.phonenumberbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phonenumberbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonenumberbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phonenumberbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonenumberbox.BorderRadius = 1;
            this.phonenumberbox.BorderThickness = 1;
            this.phonenumberbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonenumberbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.phonenumberbox.DefaultText = "";
            this.phonenumberbox.FillColor = System.Drawing.Color.White;
            this.phonenumberbox.HideSelection = true;
            this.phonenumberbox.IconLeft = null;
            this.phonenumberbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox.IconPadding = 10;
            this.phonenumberbox.IconRight = null;
            this.phonenumberbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox.Lines = new string[0];
            this.phonenumberbox.Location = new System.Drawing.Point(127, 203);
            this.phonenumberbox.MaxLength = 32767;
            this.phonenumberbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonenumberbox.Modified = false;
            this.phonenumberbox.Multiline = false;
            this.phonenumberbox.Name = "phonenumberbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonenumberbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox.OnIdleState = stateProperties8;
            this.phonenumberbox.Padding = new System.Windows.Forms.Padding(3);
            this.phonenumberbox.PasswordChar = '\0';
            this.phonenumberbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phonenumberbox.PlaceholderText = "Enter text";
            this.phonenumberbox.ReadOnly = false;
            this.phonenumberbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonenumberbox.SelectedText = "";
            this.phonenumberbox.SelectionLength = 0;
            this.phonenumberbox.SelectionStart = 0;
            this.phonenumberbox.ShortcutsEnabled = true;
            this.phonenumberbox.Size = new System.Drawing.Size(260, 37);
            this.phonenumberbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonenumberbox.TabIndex = 3;
            this.phonenumberbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonenumberbox.TextMarginBottom = 0;
            this.phonenumberbox.TextMarginLeft = 3;
            this.phonenumberbox.TextMarginTop = 0;
            this.phonenumberbox.TextPlaceholder = "Enter text";
            this.phonenumberbox.UseSystemPasswordChar = false;
            this.phonenumberbox.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(127, 180);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(117, 20);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Phone Number : ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cusnamebox
            // 
            this.cusnamebox.AcceptsReturn = false;
            this.cusnamebox.AcceptsTab = false;
            this.cusnamebox.AnimationSpeed = 200;
            this.cusnamebox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cusnamebox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cusnamebox.BackColor = System.Drawing.Color.Transparent;
            this.cusnamebox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cusnamebox.BackgroundImage")));
            this.cusnamebox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cusnamebox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cusnamebox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cusnamebox.BorderColorIdle = System.Drawing.Color.Silver;
            this.cusnamebox.BorderRadius = 1;
            this.cusnamebox.BorderThickness = 1;
            this.cusnamebox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cusnamebox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cusnamebox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cusnamebox.DefaultText = "";
            this.cusnamebox.FillColor = System.Drawing.Color.White;
            this.cusnamebox.HideSelection = true;
            this.cusnamebox.IconLeft = null;
            this.cusnamebox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cusnamebox.IconPadding = 10;
            this.cusnamebox.IconRight = null;
            this.cusnamebox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cusnamebox.Lines = new string[0];
            this.cusnamebox.Location = new System.Drawing.Point(127, 135);
            this.cusnamebox.MaxLength = 32767;
            this.cusnamebox.MinimumSize = new System.Drawing.Size(1, 1);
            this.cusnamebox.Modified = false;
            this.cusnamebox.Multiline = false;
            this.cusnamebox.Name = "cusnamebox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cusnamebox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cusnamebox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cusnamebox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cusnamebox.OnIdleState = stateProperties12;
            this.cusnamebox.Padding = new System.Windows.Forms.Padding(3);
            this.cusnamebox.PasswordChar = '\0';
            this.cusnamebox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cusnamebox.PlaceholderText = "Enter text";
            this.cusnamebox.ReadOnly = false;
            this.cusnamebox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cusnamebox.SelectedText = "";
            this.cusnamebox.SelectionLength = 0;
            this.cusnamebox.SelectionStart = 0;
            this.cusnamebox.ShortcutsEnabled = true;
            this.cusnamebox.Size = new System.Drawing.Size(260, 37);
            this.cusnamebox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cusnamebox.TabIndex = 1;
            this.cusnamebox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cusnamebox.TextMarginBottom = 0;
            this.cusnamebox.TextMarginLeft = 3;
            this.cusnamebox.TextMarginTop = 0;
            this.cusnamebox.TextPlaceholder = "Enter text";
            this.cusnamebox.UseSystemPasswordChar = false;
            this.cusnamebox.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(127, 112);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(126, 20);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Customer Name :";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage2.Controls.Add(this.label1);
            this.tabPage2.Controls.Add(this.searchbtn);
            this.tabPage2.Controls.Add(this.dataGridView1);
            this.tabPage2.Controls.Add(this.searchbox);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(876, 608);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Manage Customer";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(281, 49);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(135, 20);
            this.label1.TabIndex = 18;
            this.label1.Text = "Customer Name :";
            // 
            // searchbtn
            // 
            this.searchbtn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.searchbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchbtn.BackgroundImage")));
            this.searchbtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.searchbtn.FlatAppearance.BorderSize = 0;
            this.searchbtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.searchbtn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.searchbtn.Location = new System.Drawing.Point(551, 72);
            this.searchbtn.Name = "searchbtn";
            this.searchbtn.Size = new System.Drawing.Size(39, 37);
            this.searchbtn.TabIndex = 17;
            this.searchbtn.UseVisualStyleBackColor = false;
            this.searchbtn.Click += new System.EventHandler(this.searchbtn_Click);
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(8, 124);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(860, 413);
            this.dataGridView1.TabIndex = 16;
            this.dataGridView1.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_CellClick);
            // 
            // searchbox
            // 
            this.searchbox.AcceptsReturn = false;
            this.searchbox.AcceptsTab = false;
            this.searchbox.AnimationSpeed = 200;
            this.searchbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchbox.BackColor = System.Drawing.Color.Transparent;
            this.searchbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchbox.BackgroundImage")));
            this.searchbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.searchbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.searchbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchbox.BorderRadius = 1;
            this.searchbox.BorderThickness = 1;
            this.searchbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.searchbox.DefaultText = "";
            this.searchbox.FillColor = System.Drawing.Color.White;
            this.searchbox.HideSelection = true;
            this.searchbox.IconLeft = null;
            this.searchbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox.IconPadding = 10;
            this.searchbox.IconRight = null;
            this.searchbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox.Lines = new string[0];
            this.searchbox.Location = new System.Drawing.Point(285, 72);
            this.searchbox.MaxLength = 32767;
            this.searchbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchbox.Modified = false;
            this.searchbox.Multiline = false;
            this.searchbox.Name = "searchbox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox.OnIdleState = stateProperties16;
            this.searchbox.Padding = new System.Windows.Forms.Padding(3);
            this.searchbox.PasswordChar = '\0';
            this.searchbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchbox.PlaceholderText = "Enter text";
            this.searchbox.ReadOnly = false;
            this.searchbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchbox.SelectedText = "";
            this.searchbox.SelectionLength = 0;
            this.searchbox.SelectionStart = 0;
            this.searchbox.ShortcutsEnabled = true;
            this.searchbox.Size = new System.Drawing.Size(260, 37);
            this.searchbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchbox.TabIndex = 15;
            this.searchbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchbox.TextMarginBottom = 0;
            this.searchbox.TextMarginLeft = 3;
            this.searchbox.TextMarginTop = 0;
            this.searchbox.TextPlaceholder = "Enter text";
            this.searchbox.UseSystemPasswordChar = false;
            this.searchbox.WordWrap = true;
            // 
            // tabPage3
            // 
            this.tabPage3.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage3.Controls.Add(this.idbox);
            this.tabPage3.Controls.Add(this.bunifuLabel4);
            this.tabPage3.Controls.Add(this.deletebtn);
            this.tabPage3.Controls.Add(this.updatebtn);
            this.tabPage3.Controls.Add(this.addressbox1);
            this.tabPage3.Controls.Add(this.bunifuLabel5);
            this.tabPage3.Controls.Add(this.phonenumberbox1);
            this.tabPage3.Controls.Add(this.bunifuLabel6);
            this.tabPage3.Controls.Add(this.cusnamebox1);
            this.tabPage3.Controls.Add(this.bunifuLabel7);
            this.tabPage3.Location = new System.Drawing.Point(4, 4);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(876, 608);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Update and Delete Customer";
            // 
            // idbox
            // 
            this.idbox.AcceptsReturn = false;
            this.idbox.AcceptsTab = false;
            this.idbox.AnimationSpeed = 200;
            this.idbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idbox.BackColor = System.Drawing.Color.Transparent;
            this.idbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idbox.BackgroundImage")));
            this.idbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.idbox.BorderRadius = 1;
            this.idbox.BorderThickness = 1;
            this.idbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.idbox.DefaultText = "";
            this.idbox.FillColor = System.Drawing.Color.White;
            this.idbox.HideSelection = true;
            this.idbox.IconLeft = null;
            this.idbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idbox.IconPadding = 10;
            this.idbox.IconRight = null;
            this.idbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idbox.Lines = new string[0];
            this.idbox.Location = new System.Drawing.Point(393, 203);
            this.idbox.MaxLength = 32767;
            this.idbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.idbox.Modified = false;
            this.idbox.Multiline = false;
            this.idbox.Name = "idbox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idbox.OnIdleState = stateProperties20;
            this.idbox.Padding = new System.Windows.Forms.Padding(3);
            this.idbox.PasswordChar = '\0';
            this.idbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idbox.PlaceholderText = "Enter text";
            this.idbox.ReadOnly = true;
            this.idbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idbox.SelectedText = "";
            this.idbox.SelectionLength = 0;
            this.idbox.SelectionStart = 0;
            this.idbox.ShortcutsEnabled = true;
            this.idbox.Size = new System.Drawing.Size(106, 37);
            this.idbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idbox.TabIndex = 16;
            this.idbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idbox.TextMarginBottom = 0;
            this.idbox.TextMarginLeft = 3;
            this.idbox.TextMarginTop = 0;
            this.idbox.TextPlaceholder = "Enter text";
            this.idbox.UseSystemPasswordChar = false;
            this.idbox.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(393, 180);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(21, 20);
            this.bunifuLabel4.TabIndex = 15;
            this.bunifuLabel4.Text = "id : ";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // deletebtn
            // 
            this.deletebtn.AllowAnimations = true;
            this.deletebtn.AllowMouseEffects = true;
            this.deletebtn.AllowToggling = false;
            this.deletebtn.AnimationSpeed = 200;
            this.deletebtn.AutoGenerateColors = false;
            this.deletebtn.AutoRoundBorders = false;
            this.deletebtn.AutoSizeLeftIcon = true;
            this.deletebtn.AutoSizeRightIcon = true;
            this.deletebtn.BackColor = System.Drawing.Color.Transparent;
            this.deletebtn.BackColor1 = System.Drawing.Color.IndianRed;
            this.deletebtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deletebtn.BackgroundImage")));
            this.deletebtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deletebtn.ButtonText = "Delete";
            this.deletebtn.ButtonTextMarginLeft = 0;
            this.deletebtn.ColorContrastOnClick = 45;
            this.deletebtn.ColorContrastOnHover = 45;
            this.deletebtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.deletebtn.CustomizableEdges = borderEdges2;
            this.deletebtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deletebtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deletebtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deletebtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deletebtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.deletebtn.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.deletebtn.ForeColor = System.Drawing.Color.White;
            this.deletebtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deletebtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deletebtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deletebtn.IconMarginLeft = 11;
            this.deletebtn.IconPadding = 10;
            this.deletebtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deletebtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deletebtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deletebtn.IconSize = 25;
            this.deletebtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.deletebtn.IdleBorderRadius = 1;
            this.deletebtn.IdleBorderThickness = 1;
            this.deletebtn.IdleFillColor = System.Drawing.Color.IndianRed;
            this.deletebtn.IdleIconLeftImage = null;
            this.deletebtn.IdleIconRightImage = null;
            this.deletebtn.IndicateFocus = false;
            this.deletebtn.Location = new System.Drawing.Point(234, 404);
            this.deletebtn.Name = "deletebtn";
            this.deletebtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deletebtn.OnDisabledState.BorderRadius = 1;
            this.deletebtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deletebtn.OnDisabledState.BorderThickness = 1;
            this.deletebtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deletebtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deletebtn.OnDisabledState.IconLeftImage = null;
            this.deletebtn.OnDisabledState.IconRightImage = null;
            this.deletebtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.deletebtn.onHoverState.BorderRadius = 1;
            this.deletebtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deletebtn.onHoverState.BorderThickness = 1;
            this.deletebtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.deletebtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deletebtn.onHoverState.IconLeftImage = null;
            this.deletebtn.onHoverState.IconRightImage = null;
            this.deletebtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.deletebtn.OnIdleState.BorderRadius = 1;
            this.deletebtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deletebtn.OnIdleState.BorderThickness = 1;
            this.deletebtn.OnIdleState.FillColor = System.Drawing.Color.IndianRed;
            this.deletebtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.deletebtn.OnIdleState.IconLeftImage = null;
            this.deletebtn.OnIdleState.IconRightImage = null;
            this.deletebtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.deletebtn.OnPressedState.BorderRadius = 1;
            this.deletebtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deletebtn.OnPressedState.BorderThickness = 1;
            this.deletebtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.deletebtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deletebtn.OnPressedState.IconLeftImage = null;
            this.deletebtn.OnPressedState.IconRightImage = null;
            this.deletebtn.Size = new System.Drawing.Size(101, 39);
            this.deletebtn.TabIndex = 14;
            this.deletebtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.deletebtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deletebtn.TextMarginLeft = 0;
            this.deletebtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.deletebtn.UseDefaultRadiusAndThickness = true;
            this.deletebtn.Click += new System.EventHandler(this.deletebtn_Click);
            // 
            // updatebtn
            // 
            this.updatebtn.AllowAnimations = true;
            this.updatebtn.AllowMouseEffects = true;
            this.updatebtn.AllowToggling = false;
            this.updatebtn.AnimationSpeed = 200;
            this.updatebtn.AutoGenerateColors = false;
            this.updatebtn.AutoRoundBorders = false;
            this.updatebtn.AutoSizeLeftIcon = true;
            this.updatebtn.AutoSizeRightIcon = true;
            this.updatebtn.BackColor = System.Drawing.Color.Transparent;
            this.updatebtn.BackColor1 = System.Drawing.Color.SteelBlue;
            this.updatebtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("updatebtn.BackgroundImage")));
            this.updatebtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updatebtn.ButtonText = "Update";
            this.updatebtn.ButtonTextMarginLeft = 0;
            this.updatebtn.ColorContrastOnClick = 45;
            this.updatebtn.ColorContrastOnHover = 45;
            this.updatebtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.updatebtn.CustomizableEdges = borderEdges3;
            this.updatebtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.updatebtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updatebtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updatebtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updatebtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.updatebtn.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.updatebtn.ForeColor = System.Drawing.Color.White;
            this.updatebtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.updatebtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.updatebtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.updatebtn.IconMarginLeft = 11;
            this.updatebtn.IconPadding = 10;
            this.updatebtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.updatebtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.updatebtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.updatebtn.IconSize = 25;
            this.updatebtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.updatebtn.IdleBorderRadius = 1;
            this.updatebtn.IdleBorderThickness = 1;
            this.updatebtn.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.updatebtn.IdleIconLeftImage = null;
            this.updatebtn.IdleIconRightImage = null;
            this.updatebtn.IndicateFocus = false;
            this.updatebtn.Location = new System.Drawing.Point(127, 404);
            this.updatebtn.Name = "updatebtn";
            this.updatebtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updatebtn.OnDisabledState.BorderRadius = 1;
            this.updatebtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updatebtn.OnDisabledState.BorderThickness = 1;
            this.updatebtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updatebtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updatebtn.OnDisabledState.IconLeftImage = null;
            this.updatebtn.OnDisabledState.IconRightImage = null;
            this.updatebtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.updatebtn.onHoverState.BorderRadius = 1;
            this.updatebtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updatebtn.onHoverState.BorderThickness = 1;
            this.updatebtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.updatebtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.updatebtn.onHoverState.IconLeftImage = null;
            this.updatebtn.onHoverState.IconRightImage = null;
            this.updatebtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.updatebtn.OnIdleState.BorderRadius = 1;
            this.updatebtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updatebtn.OnIdleState.BorderThickness = 1;
            this.updatebtn.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.updatebtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.updatebtn.OnIdleState.IconLeftImage = null;
            this.updatebtn.OnIdleState.IconRightImage = null;
            this.updatebtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.updatebtn.OnPressedState.BorderRadius = 1;
            this.updatebtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updatebtn.OnPressedState.BorderThickness = 1;
            this.updatebtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.updatebtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.updatebtn.OnPressedState.IconLeftImage = null;
            this.updatebtn.OnPressedState.IconRightImage = null;
            this.updatebtn.Size = new System.Drawing.Size(101, 39);
            this.updatebtn.TabIndex = 13;
            this.updatebtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.updatebtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.updatebtn.TextMarginLeft = 0;
            this.updatebtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.updatebtn.UseDefaultRadiusAndThickness = true;
            this.updatebtn.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // addressbox1
            // 
            this.addressbox1.AcceptsReturn = false;
            this.addressbox1.AcceptsTab = false;
            this.addressbox1.AnimationSpeed = 200;
            this.addressbox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressbox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressbox1.BackColor = System.Drawing.Color.Transparent;
            this.addressbox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressbox1.BackgroundImage")));
            this.addressbox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addressbox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressbox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addressbox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressbox1.BorderRadius = 1;
            this.addressbox1.BorderThickness = 1;
            this.addressbox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressbox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressbox1.DefaultText = "";
            this.addressbox1.FillColor = System.Drawing.Color.White;
            this.addressbox1.HideSelection = true;
            this.addressbox1.IconLeft = null;
            this.addressbox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox1.IconPadding = 10;
            this.addressbox1.IconRight = null;
            this.addressbox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox1.Lines = new string[0];
            this.addressbox1.Location = new System.Drawing.Point(127, 268);
            this.addressbox1.MaxLength = 32767;
            this.addressbox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressbox1.Modified = false;
            this.addressbox1.Multiline = false;
            this.addressbox1.Name = "addressbox1";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox1.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressbox1.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox1.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox1.OnIdleState = stateProperties24;
            this.addressbox1.Padding = new System.Windows.Forms.Padding(3);
            this.addressbox1.PasswordChar = '\0';
            this.addressbox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressbox1.PlaceholderText = "Enter text";
            this.addressbox1.ReadOnly = false;
            this.addressbox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressbox1.SelectedText = "";
            this.addressbox1.SelectionLength = 0;
            this.addressbox1.SelectionStart = 0;
            this.addressbox1.ShortcutsEnabled = true;
            this.addressbox1.Size = new System.Drawing.Size(634, 107);
            this.addressbox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressbox1.TabIndex = 12;
            this.addressbox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressbox1.TextMarginBottom = 0;
            this.addressbox1.TextMarginLeft = 3;
            this.addressbox1.TextMarginTop = 0;
            this.addressbox1.TextPlaceholder = "Enter text";
            this.addressbox1.UseSystemPasswordChar = false;
            this.addressbox1.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(127, 245);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(66, 20);
            this.bunifuLabel5.TabIndex = 11;
            this.bunifuLabel5.Text = "Address : ";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // phonenumberbox1
            // 
            this.phonenumberbox1.AcceptsReturn = false;
            this.phonenumberbox1.AcceptsTab = false;
            this.phonenumberbox1.AnimationSpeed = 200;
            this.phonenumberbox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonenumberbox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonenumberbox1.BackColor = System.Drawing.Color.Transparent;
            this.phonenumberbox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonenumberbox1.BackgroundImage")));
            this.phonenumberbox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phonenumberbox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonenumberbox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phonenumberbox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonenumberbox1.BorderRadius = 1;
            this.phonenumberbox1.BorderThickness = 1;
            this.phonenumberbox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonenumberbox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.phonenumberbox1.DefaultText = "";
            this.phonenumberbox1.FillColor = System.Drawing.Color.White;
            this.phonenumberbox1.HideSelection = true;
            this.phonenumberbox1.IconLeft = null;
            this.phonenumberbox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox1.IconPadding = 10;
            this.phonenumberbox1.IconRight = null;
            this.phonenumberbox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox1.Lines = new string[0];
            this.phonenumberbox1.Location = new System.Drawing.Point(127, 203);
            this.phonenumberbox1.MaxLength = 32767;
            this.phonenumberbox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonenumberbox1.Modified = false;
            this.phonenumberbox1.Multiline = false;
            this.phonenumberbox1.Name = "phonenumberbox1";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox1.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonenumberbox1.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox1.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox1.OnIdleState = stateProperties28;
            this.phonenumberbox1.Padding = new System.Windows.Forms.Padding(3);
            this.phonenumberbox1.PasswordChar = '\0';
            this.phonenumberbox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phonenumberbox1.PlaceholderText = "Enter text";
            this.phonenumberbox1.ReadOnly = false;
            this.phonenumberbox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonenumberbox1.SelectedText = "";
            this.phonenumberbox1.SelectionLength = 0;
            this.phonenumberbox1.SelectionStart = 0;
            this.phonenumberbox1.ShortcutsEnabled = true;
            this.phonenumberbox1.Size = new System.Drawing.Size(260, 37);
            this.phonenumberbox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonenumberbox1.TabIndex = 10;
            this.phonenumberbox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonenumberbox1.TextMarginBottom = 0;
            this.phonenumberbox1.TextMarginLeft = 3;
            this.phonenumberbox1.TextMarginTop = 0;
            this.phonenumberbox1.TextPlaceholder = "Enter text";
            this.phonenumberbox1.UseSystemPasswordChar = false;
            this.phonenumberbox1.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(127, 180);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(117, 20);
            this.bunifuLabel6.TabIndex = 9;
            this.bunifuLabel6.Text = "Phone Number : ";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cusnamebox1
            // 
            this.cusnamebox1.AcceptsReturn = false;
            this.cusnamebox1.AcceptsTab = false;
            this.cusnamebox1.AnimationSpeed = 200;
            this.cusnamebox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cusnamebox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cusnamebox1.BackColor = System.Drawing.Color.Transparent;
            this.cusnamebox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cusnamebox1.BackgroundImage")));
            this.cusnamebox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cusnamebox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cusnamebox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cusnamebox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.cusnamebox1.BorderRadius = 1;
            this.cusnamebox1.BorderThickness = 1;
            this.cusnamebox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cusnamebox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cusnamebox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cusnamebox1.DefaultText = "";
            this.cusnamebox1.FillColor = System.Drawing.Color.White;
            this.cusnamebox1.HideSelection = true;
            this.cusnamebox1.IconLeft = null;
            this.cusnamebox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cusnamebox1.IconPadding = 10;
            this.cusnamebox1.IconRight = null;
            this.cusnamebox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cusnamebox1.Lines = new string[0];
            this.cusnamebox1.Location = new System.Drawing.Point(127, 135);
            this.cusnamebox1.MaxLength = 32767;
            this.cusnamebox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.cusnamebox1.Modified = false;
            this.cusnamebox1.Multiline = false;
            this.cusnamebox1.Name = "cusnamebox1";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cusnamebox1.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cusnamebox1.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cusnamebox1.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cusnamebox1.OnIdleState = stateProperties32;
            this.cusnamebox1.Padding = new System.Windows.Forms.Padding(3);
            this.cusnamebox1.PasswordChar = '\0';
            this.cusnamebox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cusnamebox1.PlaceholderText = "Enter text";
            this.cusnamebox1.ReadOnly = false;
            this.cusnamebox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cusnamebox1.SelectedText = "";
            this.cusnamebox1.SelectionLength = 0;
            this.cusnamebox1.SelectionStart = 0;
            this.cusnamebox1.ShortcutsEnabled = true;
            this.cusnamebox1.Size = new System.Drawing.Size(260, 37);
            this.cusnamebox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cusnamebox1.TabIndex = 8;
            this.cusnamebox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cusnamebox1.TextMarginBottom = 0;
            this.cusnamebox1.TextMarginLeft = 3;
            this.cusnamebox1.TextMarginTop = 0;
            this.cusnamebox1.TextPlaceholder = "Enter text";
            this.cusnamebox1.UseSystemPasswordChar = false;
            this.cusnamebox1.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(127, 112);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(126, 20);
            this.bunifuLabel7.TabIndex = 7;
            this.bunifuLabel7.Text = "Customer Name :";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Customer
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tabControl1);
            this.Name = "Customer";
            this.Size = new System.Drawing.Size(1108, 790);
            this.Load += new System.EventHandler(this.Customer_Load);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addbtn;
        private Bunifu.UI.WinForms.BunifuTextBox addressbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox phonenumberbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox cusnamebox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton deletebtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton updatebtn;
        private Bunifu.UI.WinForms.BunifuTextBox addressbox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox phonenumberbox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox cusnamebox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button searchbtn;
        private System.Windows.Forms.DataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuTextBox searchbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox idbox;
    }
}
