namespace WindowsFormsApp1.UserControls
{
    partial class Vendor
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Vendor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addressbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.phonenumberbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.vendorbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.searchbtn = new System.Windows.Forms.Button();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.searchbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.idbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addressbox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.phonenumberbox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.vendorbox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.tabPage3.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Location = new System.Drawing.Point(212, 78);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(884, 634);
            this.tabControl1.TabIndex = 3;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage1.Controls.Add(this.bunifuButton1);
            this.tabPage1.Controls.Add(this.addressbox);
            this.tabPage1.Controls.Add(this.bunifuLabel3);
            this.tabPage1.Controls.Add(this.phonenumberbox);
            this.tabPage1.Controls.Add(this.bunifuLabel2);
            this.tabPage1.Controls.Add(this.vendorbox);
            this.tabPage1.Controls.Add(this.bunifuLabel1);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(876, 608);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Add Vendor";
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.SteelBlue;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Add";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(127, 404);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(101, 39);
            this.bunifuButton1.TabIndex = 6;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // addressbox
            // 
            this.addressbox.AcceptsReturn = false;
            this.addressbox.AcceptsTab = false;
            this.addressbox.AnimationSpeed = 200;
            this.addressbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressbox.BackColor = System.Drawing.Color.Transparent;
            this.addressbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressbox.BackgroundImage")));
            this.addressbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addressbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addressbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressbox.BorderRadius = 1;
            this.addressbox.BorderThickness = 1;
            this.addressbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressbox.DefaultText = "";
            this.addressbox.FillColor = System.Drawing.Color.White;
            this.addressbox.HideSelection = true;
            this.addressbox.IconLeft = null;
            this.addressbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox.IconPadding = 10;
            this.addressbox.IconRight = null;
            this.addressbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox.Lines = new string[0];
            this.addressbox.Location = new System.Drawing.Point(127, 268);
            this.addressbox.MaxLength = 32767;
            this.addressbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressbox.Modified = false;
            this.addressbox.Multiline = false;
            this.addressbox.Name = "addressbox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox.OnIdleState = stateProperties4;
            this.addressbox.Padding = new System.Windows.Forms.Padding(3);
            this.addressbox.PasswordChar = '\0';
            this.addressbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressbox.PlaceholderText = "Enter text";
            this.addressbox.ReadOnly = false;
            this.addressbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressbox.SelectedText = "";
            this.addressbox.SelectionLength = 0;
            this.addressbox.SelectionStart = 0;
            this.addressbox.ShortcutsEnabled = true;
            this.addressbox.Size = new System.Drawing.Size(634, 107);
            this.addressbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressbox.TabIndex = 5;
            this.addressbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressbox.TextMarginBottom = 0;
            this.addressbox.TextMarginLeft = 3;
            this.addressbox.TextMarginTop = 0;
            this.addressbox.TextPlaceholder = "Enter text";
            this.addressbox.UseSystemPasswordChar = false;
            this.addressbox.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(127, 245);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(66, 20);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Address : ";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // phonenumberbox
            // 
            this.phonenumberbox.AcceptsReturn = false;
            this.phonenumberbox.AcceptsTab = false;
            this.phonenumberbox.AnimationSpeed = 200;
            this.phonenumberbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonenumberbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonenumberbox.BackColor = System.Drawing.Color.Transparent;
            this.phonenumberbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonenumberbox.BackgroundImage")));
            this.phonenumberbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phonenumberbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonenumberbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phonenumberbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonenumberbox.BorderRadius = 1;
            this.phonenumberbox.BorderThickness = 1;
            this.phonenumberbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonenumberbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.phonenumberbox.DefaultText = "";
            this.phonenumberbox.FillColor = System.Drawing.Color.White;
            this.phonenumberbox.HideSelection = true;
            this.phonenumberbox.IconLeft = null;
            this.phonenumberbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox.IconPadding = 10;
            this.phonenumberbox.IconRight = null;
            this.phonenumberbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox.Lines = new string[0];
            this.phonenumberbox.Location = new System.Drawing.Point(127, 203);
            this.phonenumberbox.MaxLength = 32767;
            this.phonenumberbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonenumberbox.Modified = false;
            this.phonenumberbox.Multiline = false;
            this.phonenumberbox.Name = "phonenumberbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonenumberbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox.OnIdleState = stateProperties8;
            this.phonenumberbox.Padding = new System.Windows.Forms.Padding(3);
            this.phonenumberbox.PasswordChar = '\0';
            this.phonenumberbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phonenumberbox.PlaceholderText = "Enter text";
            this.phonenumberbox.ReadOnly = false;
            this.phonenumberbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonenumberbox.SelectedText = "";
            this.phonenumberbox.SelectionLength = 0;
            this.phonenumberbox.SelectionStart = 0;
            this.phonenumberbox.ShortcutsEnabled = true;
            this.phonenumberbox.Size = new System.Drawing.Size(260, 37);
            this.phonenumberbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonenumberbox.TabIndex = 3;
            this.phonenumberbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonenumberbox.TextMarginBottom = 0;
            this.phonenumberbox.TextMarginLeft = 3;
            this.phonenumberbox.TextMarginTop = 0;
            this.phonenumberbox.TextPlaceholder = "Enter text";
            this.phonenumberbox.UseSystemPasswordChar = false;
            this.phonenumberbox.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(127, 180);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(117, 20);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Phone Number : ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // vendorbox
            // 
            this.vendorbox.AcceptsReturn = false;
            this.vendorbox.AcceptsTab = false;
            this.vendorbox.AnimationSpeed = 200;
            this.vendorbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.vendorbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.vendorbox.BackColor = System.Drawing.Color.Transparent;
            this.vendorbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("vendorbox.BackgroundImage")));
            this.vendorbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.vendorbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.vendorbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.vendorbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.vendorbox.BorderRadius = 1;
            this.vendorbox.BorderThickness = 1;
            this.vendorbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.vendorbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.vendorbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.vendorbox.DefaultText = "";
            this.vendorbox.FillColor = System.Drawing.Color.White;
            this.vendorbox.HideSelection = true;
            this.vendorbox.IconLeft = null;
            this.vendorbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.vendorbox.IconPadding = 10;
            this.vendorbox.IconRight = null;
            this.vendorbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.vendorbox.Lines = new string[0];
            this.vendorbox.Location = new System.Drawing.Point(127, 135);
            this.vendorbox.MaxLength = 32767;
            this.vendorbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.vendorbox.Modified = false;
            this.vendorbox.Multiline = false;
            this.vendorbox.Name = "vendorbox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.vendorbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.vendorbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.vendorbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.vendorbox.OnIdleState = stateProperties12;
            this.vendorbox.Padding = new System.Windows.Forms.Padding(3);
            this.vendorbox.PasswordChar = '\0';
            this.vendorbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.vendorbox.PlaceholderText = "Enter text";
            this.vendorbox.ReadOnly = false;
            this.vendorbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.vendorbox.SelectedText = "";
            this.vendorbox.SelectionLength = 0;
            this.vendorbox.SelectionStart = 0;
            this.vendorbox.ShortcutsEnabled = true;
            this.vendorbox.Size = new System.Drawing.Size(260, 37);
            this.vendorbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.vendorbox.TabIndex = 1;
            this.vendorbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.vendorbox.TextMarginBottom = 0;
            this.vendorbox.TextMarginLeft = 3;
            this.vendorbox.TextMarginTop = 0;
            this.vendorbox.TextPlaceholder = "Enter text";
            this.vendorbox.UseSystemPasswordChar = false;
            this.vendorbox.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(127, 112);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(111, 20);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Vendor Name : ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage2.Controls.Add(this.searchbtn);
            this.tabPage2.Controls.Add(this.dataGridView1);
            this.tabPage2.Controls.Add(this.searchbox);
            this.tabPage2.Controls.Add(this.bunifuLabel4);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(876, 608);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Manage Vendor";
            // 
            // searchbtn
            // 
            this.searchbtn.BackColor = System.Drawing.Color.WhiteSmoke;
            this.searchbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchbtn.BackgroundImage")));
            this.searchbtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.searchbtn.FlatAppearance.BorderSize = 0;
            this.searchbtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.searchbtn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.searchbtn.Location = new System.Drawing.Point(548, 94);
            this.searchbtn.Name = "searchbtn";
            this.searchbtn.Size = new System.Drawing.Size(39, 37);
            this.searchbtn.TabIndex = 14;
            this.searchbtn.UseVisualStyleBackColor = false;
            this.searchbtn.Click += new System.EventHandler(this.searchbtn_Click);
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(9, 154);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(860, 413);
            this.dataGridView1.TabIndex = 4;
            this.dataGridView1.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_CellClick);
            // 
            // searchbox
            // 
            this.searchbox.AcceptsReturn = false;
            this.searchbox.AcceptsTab = false;
            this.searchbox.AnimationSpeed = 200;
            this.searchbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchbox.BackColor = System.Drawing.Color.Transparent;
            this.searchbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchbox.BackgroundImage")));
            this.searchbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.searchbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.searchbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchbox.BorderRadius = 1;
            this.searchbox.BorderThickness = 1;
            this.searchbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.searchbox.DefaultText = "";
            this.searchbox.FillColor = System.Drawing.Color.White;
            this.searchbox.HideSelection = true;
            this.searchbox.IconLeft = null;
            this.searchbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox.IconPadding = 10;
            this.searchbox.IconRight = null;
            this.searchbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox.Lines = new string[0];
            this.searchbox.Location = new System.Drawing.Point(282, 94);
            this.searchbox.MaxLength = 32767;
            this.searchbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchbox.Modified = false;
            this.searchbox.Multiline = false;
            this.searchbox.Name = "searchbox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox.OnIdleState = stateProperties16;
            this.searchbox.Padding = new System.Windows.Forms.Padding(3);
            this.searchbox.PasswordChar = '\0';
            this.searchbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchbox.PlaceholderText = "Enter text";
            this.searchbox.ReadOnly = false;
            this.searchbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchbox.SelectedText = "";
            this.searchbox.SelectionLength = 0;
            this.searchbox.SelectionStart = 0;
            this.searchbox.ShortcutsEnabled = true;
            this.searchbox.Size = new System.Drawing.Size(260, 37);
            this.searchbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchbox.TabIndex = 3;
            this.searchbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchbox.TextMarginBottom = 0;
            this.searchbox.TextMarginLeft = 3;
            this.searchbox.TextMarginTop = 0;
            this.searchbox.TextPlaceholder = "Enter text";
            this.searchbox.UseSystemPasswordChar = false;
            this.searchbox.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(282, 71);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(111, 20);
            this.bunifuLabel4.TabIndex = 2;
            this.bunifuLabel4.Text = "Vendor Name : ";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tabPage3
            // 
            this.tabPage3.BackColor = System.Drawing.Color.WhiteSmoke;
            this.tabPage3.Controls.Add(this.idbox);
            this.tabPage3.Controls.Add(this.bunifuLabel8);
            this.tabPage3.Controls.Add(this.bunifuButton3);
            this.tabPage3.Controls.Add(this.bunifuButton2);
            this.tabPage3.Controls.Add(this.addressbox1);
            this.tabPage3.Controls.Add(this.bunifuLabel5);
            this.tabPage3.Controls.Add(this.phonenumberbox1);
            this.tabPage3.Controls.Add(this.bunifuLabel6);
            this.tabPage3.Controls.Add(this.vendorbox1);
            this.tabPage3.Controls.Add(this.bunifuLabel7);
            this.tabPage3.Location = new System.Drawing.Point(4, 4);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(876, 608);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Update and Delete Vendor";
            // 
            // idbox
            // 
            this.idbox.AcceptsReturn = false;
            this.idbox.AcceptsTab = false;
            this.idbox.AnimationSpeed = 200;
            this.idbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idbox.BackColor = System.Drawing.Color.Transparent;
            this.idbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idbox.BackgroundImage")));
            this.idbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.idbox.BorderRadius = 1;
            this.idbox.BorderThickness = 1;
            this.idbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.idbox.DefaultText = "";
            this.idbox.FillColor = System.Drawing.Color.White;
            this.idbox.HideSelection = true;
            this.idbox.IconLeft = null;
            this.idbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idbox.IconPadding = 10;
            this.idbox.IconRight = null;
            this.idbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idbox.Lines = new string[0];
            this.idbox.Location = new System.Drawing.Point(393, 203);
            this.idbox.MaxLength = 32767;
            this.idbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.idbox.Modified = false;
            this.idbox.Multiline = false;
            this.idbox.Name = "idbox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idbox.OnIdleState = stateProperties20;
            this.idbox.Padding = new System.Windows.Forms.Padding(3);
            this.idbox.PasswordChar = '\0';
            this.idbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idbox.PlaceholderText = "Enter text";
            this.idbox.ReadOnly = true;
            this.idbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idbox.SelectedText = "";
            this.idbox.SelectionLength = 0;
            this.idbox.SelectionStart = 0;
            this.idbox.ShortcutsEnabled = true;
            this.idbox.Size = new System.Drawing.Size(106, 37);
            this.idbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idbox.TabIndex = 18;
            this.idbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idbox.TextMarginBottom = 0;
            this.idbox.TextMarginLeft = 3;
            this.idbox.TextMarginTop = 0;
            this.idbox.TextPlaceholder = "Enter text";
            this.idbox.UseSystemPasswordChar = false;
            this.idbox.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(393, 180);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(21, 20);
            this.bunifuLabel8.TabIndex = 17;
            this.bunifuLabel8.Text = "id : ";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.IndianRed;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Delete";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges2;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.IdleBorderRadius = 1;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.IndianRed;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(234, 404);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.IndianRed;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(101, 39);
            this.bunifuButton3.TabIndex = 14;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.SteelBlue;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Update";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges3;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(127, 404);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(101, 39);
            this.bunifuButton2.TabIndex = 13;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // addressbox1
            // 
            this.addressbox1.AcceptsReturn = false;
            this.addressbox1.AcceptsTab = false;
            this.addressbox1.AnimationSpeed = 200;
            this.addressbox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressbox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressbox1.BackColor = System.Drawing.Color.Transparent;
            this.addressbox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressbox1.BackgroundImage")));
            this.addressbox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addressbox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressbox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addressbox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressbox1.BorderRadius = 1;
            this.addressbox1.BorderThickness = 1;
            this.addressbox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressbox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressbox1.DefaultText = "";
            this.addressbox1.FillColor = System.Drawing.Color.White;
            this.addressbox1.HideSelection = true;
            this.addressbox1.IconLeft = null;
            this.addressbox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox1.IconPadding = 10;
            this.addressbox1.IconRight = null;
            this.addressbox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressbox1.Lines = new string[0];
            this.addressbox1.Location = new System.Drawing.Point(127, 268);
            this.addressbox1.MaxLength = 32767;
            this.addressbox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressbox1.Modified = false;
            this.addressbox1.Multiline = false;
            this.addressbox1.Name = "addressbox1";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox1.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressbox1.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox1.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressbox1.OnIdleState = stateProperties24;
            this.addressbox1.Padding = new System.Windows.Forms.Padding(3);
            this.addressbox1.PasswordChar = '\0';
            this.addressbox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressbox1.PlaceholderText = "Enter text";
            this.addressbox1.ReadOnly = false;
            this.addressbox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressbox1.SelectedText = "";
            this.addressbox1.SelectionLength = 0;
            this.addressbox1.SelectionStart = 0;
            this.addressbox1.ShortcutsEnabled = true;
            this.addressbox1.Size = new System.Drawing.Size(634, 107);
            this.addressbox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressbox1.TabIndex = 12;
            this.addressbox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressbox1.TextMarginBottom = 0;
            this.addressbox1.TextMarginLeft = 3;
            this.addressbox1.TextMarginTop = 0;
            this.addressbox1.TextPlaceholder = "Enter text";
            this.addressbox1.UseSystemPasswordChar = false;
            this.addressbox1.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(127, 245);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(66, 20);
            this.bunifuLabel5.TabIndex = 11;
            this.bunifuLabel5.Text = "Address : ";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // phonenumberbox1
            // 
            this.phonenumberbox1.AcceptsReturn = false;
            this.phonenumberbox1.AcceptsTab = false;
            this.phonenumberbox1.AnimationSpeed = 200;
            this.phonenumberbox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonenumberbox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonenumberbox1.BackColor = System.Drawing.Color.Transparent;
            this.phonenumberbox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonenumberbox1.BackgroundImage")));
            this.phonenumberbox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phonenumberbox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonenumberbox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phonenumberbox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonenumberbox1.BorderRadius = 1;
            this.phonenumberbox1.BorderThickness = 1;
            this.phonenumberbox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonenumberbox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.phonenumberbox1.DefaultText = "";
            this.phonenumberbox1.FillColor = System.Drawing.Color.White;
            this.phonenumberbox1.HideSelection = true;
            this.phonenumberbox1.IconLeft = null;
            this.phonenumberbox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox1.IconPadding = 10;
            this.phonenumberbox1.IconRight = null;
            this.phonenumberbox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberbox1.Lines = new string[0];
            this.phonenumberbox1.Location = new System.Drawing.Point(127, 203);
            this.phonenumberbox1.MaxLength = 32767;
            this.phonenumberbox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonenumberbox1.Modified = false;
            this.phonenumberbox1.Multiline = false;
            this.phonenumberbox1.Name = "phonenumberbox1";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox1.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonenumberbox1.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox1.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberbox1.OnIdleState = stateProperties28;
            this.phonenumberbox1.Padding = new System.Windows.Forms.Padding(3);
            this.phonenumberbox1.PasswordChar = '\0';
            this.phonenumberbox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phonenumberbox1.PlaceholderText = "Enter text";
            this.phonenumberbox1.ReadOnly = false;
            this.phonenumberbox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonenumberbox1.SelectedText = "";
            this.phonenumberbox1.SelectionLength = 0;
            this.phonenumberbox1.SelectionStart = 0;
            this.phonenumberbox1.ShortcutsEnabled = true;
            this.phonenumberbox1.Size = new System.Drawing.Size(260, 37);
            this.phonenumberbox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonenumberbox1.TabIndex = 10;
            this.phonenumberbox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonenumberbox1.TextMarginBottom = 0;
            this.phonenumberbox1.TextMarginLeft = 3;
            this.phonenumberbox1.TextMarginTop = 0;
            this.phonenumberbox1.TextPlaceholder = "Enter text";
            this.phonenumberbox1.UseSystemPasswordChar = false;
            this.phonenumberbox1.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(127, 180);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(117, 20);
            this.bunifuLabel6.TabIndex = 9;
            this.bunifuLabel6.Text = "Phone Number : ";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // vendorbox1
            // 
            this.vendorbox1.AcceptsReturn = false;
            this.vendorbox1.AcceptsTab = false;
            this.vendorbox1.AnimationSpeed = 200;
            this.vendorbox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.vendorbox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.vendorbox1.BackColor = System.Drawing.Color.Transparent;
            this.vendorbox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("vendorbox1.BackgroundImage")));
            this.vendorbox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.vendorbox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.vendorbox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.vendorbox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.vendorbox1.BorderRadius = 1;
            this.vendorbox1.BorderThickness = 1;
            this.vendorbox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.vendorbox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.vendorbox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.vendorbox1.DefaultText = "";
            this.vendorbox1.FillColor = System.Drawing.Color.White;
            this.vendorbox1.HideSelection = true;
            this.vendorbox1.IconLeft = null;
            this.vendorbox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.vendorbox1.IconPadding = 10;
            this.vendorbox1.IconRight = null;
            this.vendorbox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.vendorbox1.Lines = new string[0];
            this.vendorbox1.Location = new System.Drawing.Point(127, 135);
            this.vendorbox1.MaxLength = 32767;
            this.vendorbox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.vendorbox1.Modified = false;
            this.vendorbox1.Multiline = false;
            this.vendorbox1.Name = "vendorbox1";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.vendorbox1.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.vendorbox1.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.vendorbox1.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.vendorbox1.OnIdleState = stateProperties32;
            this.vendorbox1.Padding = new System.Windows.Forms.Padding(3);
            this.vendorbox1.PasswordChar = '\0';
            this.vendorbox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.vendorbox1.PlaceholderText = "Enter text";
            this.vendorbox1.ReadOnly = false;
            this.vendorbox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.vendorbox1.SelectedText = "";
            this.vendorbox1.SelectionLength = 0;
            this.vendorbox1.SelectionStart = 0;
            this.vendorbox1.ShortcutsEnabled = true;
            this.vendorbox1.Size = new System.Drawing.Size(260, 37);
            this.vendorbox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.vendorbox1.TabIndex = 8;
            this.vendorbox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.vendorbox1.TextMarginBottom = 0;
            this.vendorbox1.TextMarginLeft = 3;
            this.vendorbox1.TextMarginTop = 0;
            this.vendorbox1.TextPlaceholder = "Enter text";
            this.vendorbox1.UseSystemPasswordChar = false;
            this.vendorbox1.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(127, 112);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(111, 20);
            this.bunifuLabel7.TabIndex = 7;
            this.bunifuLabel7.Text = "Vendor Name : ";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Vendor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tabControl1);
            this.Name = "Vendor";
            this.Size = new System.Drawing.Size(1108, 790);
            this.Load += new System.EventHandler(this.Vendor_Load);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuTextBox addressbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox phonenumberbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox vendorbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.DataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuTextBox searchbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private System.Windows.Forms.TabPage tabPage3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuTextBox addressbox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox phonenumberbox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox vendorbox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private System.Windows.Forms.Button searchbtn;
        private Bunifu.UI.WinForms.BunifuTextBox idbox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
    }
}
